version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - nginx
    image: php
    container_name: php-app-service
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: social_client
      DB_USERNAME: han
      DB_PASSWORD: secret
      DB_WRITE_HOST: db
      DB_READ_HOST: db
    networks:
      - socialmedia

  db:
    image: mysql:8.0.33
    container_name: mysql-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: social_client
      MYSQL_USER: han
      MYSQL_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - socialmedia

  nginx:
    image: nginx:alpine
    container_name: nginx-web-server
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - socialmedia

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8888:80
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306      
      MYSQL_USER: han     
      MYSQL_PASSWORD: secret 
      UPLOAD_LIMIT: 3000M
    networks:
      - socialmedia

networks:
  socialmedia:
    driver: bridge

volumes:
  mysqldata: {}
