version: '3.5'
services:
  php8.2:
    build: .
    container_name: social-media-app
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"

  database:
    image: mysql:8
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo 

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8888:80
    links:
      - database
    environment:
      PMA_HOST: database 
      PMA_PORT: 3306
      UPLOAD_LIMIT: 3000M

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db-data: {}
